# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\"P\n\nSensorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\n\n\x02pH\x18\x02 \x01(\x02\x12\x0f\n\x07\x64Oxygen\x18\x03 \x01(\x02\x12\x10\n\x08salinity\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATA._serialized_start=21
  _SENSORDATA._serialized_end=101
# @@protoc_insertion_point(module_scope)
